[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Jocs <iqi.zamora@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"  # Compatible con todos los paquetes actuales
uvicorn = "^0.34.0"
dotenv = "^0.9.9"
fastapi = "^0.115.11"
pymongo = "^4.11.2"
httpx = "^0.28.1"
pytest-asyncio = "^0.25.3"
motor = "^3.7.0"
beanie = "^1.29.0"
tenacity = "^9.1.2"
pydantic-settings = "^2.8.1"
slowapi = "^0.1.9"
pandas = "^2.2.3"
mlflow = "^3.1.1"
azure-eventhub = "^5.15.0"
azure-identity = "^1.23.1"
aiohttp = "^3.12.14"
redis = "^6.4.0"
anyio = "^4.10.0"
partial = "^1.0"
uuid-utils = "^0.12.0"
pyjwt = "^2.10.1"
pwdlib = {extras = ["argon2"], version = "^0.3.0"}
asyncpg = "^0.31.0"
pydantic = {extras = ["email"], version = "^2.12.5"}
python-multipart = "^0.0.21"
langgraph = "^1.0.9"
psycopg = {extras = ["binary", "pool"], version = "^3.3.3"}
langgraph-checkpoint-postgres = "^3.0.4"
langgraph-checkpoint-redis = "^0.3.5"
langchain = "^1.2.10"
psycopg2-binary = "^2.9.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"